resolver: lts-17.4 # For ghc 8.10.4

packages:
- .

extra-deps:
- ../../

require-stack-version: ">=1.8"

nix:
  enable: false
  pure: true
  packages: []
  shell-file: stack-shell.nix
  nix-shell-options: []
  path: []
  add-gc-roots: false


